[package]
name = "zvm"
version = "0.1.0"
edition = "2024"

[dependencies]
zeal-ast = { path = "../zeal-ast" }
zeal-core = { path = "../zeal-core" }
anyhow = { workspace = true }
bytemuck = { workspace = true }
clap = { workspace = true }


num-derive = { workspace = true }
num-traits = { workspace = true }
# phf = { version = "0.13.1", features = ["macros"], default_features = false }
thiserror = { workspace = true }
