[package]
name = "zvm-bytecode"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { version = "1.0.97", default-features = false }
zerocopy = "0.8.23"
zerocopy-derive = "0.8.23"

log = { version = "0.4.22", default-features = false }
libc = { version = "0.2.171", default-features = false }
thiserror-no-std = "2.0.2"
typeid = "1.0.3"
bytemuck = { version = "1.22.0", default-features = false, features = ["align_offset", "bytemuck_derive", "const_zeroed", "derive", "min_const_generics", "must_cast", "must_cast_extra", "pod_saturating", "transparentwrapper_extra", "zeroable_atomics", "zeroable_maybe_uninit"] }

