[package]
name = "zeal-interp"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
env_logger = "0.11.5"
log = "0.4.22"
num-derive = "0.4.2"
num-traits = "0.2.19"
thiserror = "2.0.6"
zvm = { path = "../zvm" }
zeal-ast = { path = "../zeal-ast" }
zeal-core = { path = "../zeal-core" }
phf = { version = "0.11.2", features = ["macros"] }

[dev-dependencies]
env_logger = "0.11.5"

