[package]
name = "zeal-ast"
version = "0.1.0"
edition = "2024"

[dependencies]
zeal-core = { path = "../zeal-core" }

mi_malloc = { workspace = true }
ufmt = {workspace = true }
logos = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
bytemuck = { workspace = true }
kos = { workspace = true }

[features]
default = []
std = []
