[package]
name = "zeal-ast"
version = "0.1.0"
edition = "2024"

[dependencies]

zeal-core = { path = "../zeal-core" }
logos = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
bytemuck = { workspace = true }
const_format = { workspace = true }
format_no_std = { workspace = true }
